import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css"; // Keep global styles
import Header from "@/components/layout/header";
import SideBar from "@/components/layout/sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Planingo Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className={`${poppins.variable} antialiased`}>
      <Header />
      <div className="flex h-screen overflow-hidden">
        <SideBar />
        <main className="w-full md:w-10/12 z-10 p-10 pt-44 bg-[#e5e7eb]">
          {children} {/* 👈 This is where each page inside (dashboard) will be rendered */}
        </main>
      </div>
    </div>
  );
}
